<?php
/**
 * @file
 * Install functions for the Hacked! module.
 */

/**
 * Implementation of hook_schema().
 */
function hacked_schema() {
  $tables = array();

  $tables['cache_hacked'] = drupal_get_schema_unprocessed('system', 'cache');
  $tables['cache_hacked']['description'] = 'Cache table for the Hacked! module. Holds hashes for the various projects.';

  return $tables;
}

/**
 * Implements hook_uninstall().
 */
function hacked_uninstall() {
  variable_del('hacked_selected_file_hasher');
  variable_del('hacked_cvs_cmd');
  variable_del('hacked_last_report');
}
