<?php

/**
 * @file
 * 443 Session module file
 */


/**
 * Implementation of hook_menu().
 */
function session443_menu() {
  $items['session443/denied'] = array(
    'access callback' => TRUE,
    'page callback' => 'session443_denied',
    'title' => 'Access denied',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function session443_denied() {
  $site_403_orig = variable_get('session443_site_403_orig', '');
  $req_uri = request_uri();
  if ($req_uri == '/user/login' && user_is_logged_in()) {
    drupal_set_message(t('You are already logged in.'));
    menu_set_active_item('user');
    $return = menu_execute_active_handler(NULL, FALSE);
  }
  elseif ($site_403_orig != '') {
    menu_set_active_item($site_403_orig);
    $return = menu_execute_active_handler(NULL, FALSE);
  }
  else {
    drupal_set_title(t('Access denied'));
    $return = t('You are not authorized to access this page.');
  }
  return $return;
}


function _session443_redirect() {
  header('Location: https://' . $_SERVER['HTTP_HOST'] . request_uri(), TRUE, 303);
}


function session443_form_user_login_alter(&$form, $form_state) {
  if (!$_SERVER['HTTPS']) {
    _session443_redirect();
  }
}


function session443_form_user_register_alter(&$form, $form_state) {
  if (!$_SERVER['HTTPS']) {
    _session443_redirect();
  }
}


function session443_form_user_login_block_alter(&$form, $form_state) {
  if (!$_SERVER['HTTPS']) {
    _session443_redirect();
  }
}


/**
 * Implementation of hook_mail_alter().
 */
function session443_mail_alter(&$message) {
  $module = substr($message['id'], 0, 5);
  if ($module == 'user_') {
    $message['body'] = str_replace('http://', 'https://', $message['body']);
  }
}


// vim: set filetype=php expandtab tabstop=2 shiftwidth=2 autoindent smartindent:
